all:
	go run main.go https://www.baidu.com/ \
	http://www.qq.com/ https://www.taobao.com/ https://www.tmall.com/ \
	http://www.sohu.com/ https://www.jd.com/ http://www.sina.com.cn/ \
	https://weibo.com https://www.360.cn/ https://www.csdn.net/
